//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Psico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PsicologiaEntities1 : DbContext
    {
        public PsicologiaEntities1()
            : base("name=PsicologiaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FORMULARIO> FORMULARIOS { get; set; }
        public virtual DbSet<PREGUNTA> PREGUNTAS { get; set; }
        public virtual DbSet<RESPUESTA> RESPUESTAS { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<TIPOUSUARIO> TIPOUSUARIOs { get; set; }
    }
}
