//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Psico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PREGUNTA
    {
        public int Idpregunta { get; set; }
        public int Idformulario { get; set; }
        public string Pregunta1 { get; set; }
        public Nullable<int> Idrespuesta { get; set; }
    }
}
