//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Psico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESPUESTA
    {
        public int Idrespuesta { get; set; }
        public int Idusuario { get; set; }
        public string Respuesta1 { get; set; }
    }
}
