//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Psico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Idusuario { get; set; }
        public int Idtipousuario { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Ultimavez { get; set; }
        public string Correo { get; set; }
    }
}
